# spell-checker: ignore subosito

name: Release to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    name: Test and Release
    runs-on: ubuntu-latest
    environment: pub.dev
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - name: Restore packages
        run: |
          dart pub global activate melos
          melos bootstrap
      - name: Analyze
        run: melos run analyze
      - name: Test
        run: melos run test
      - name: Publish
        working-directory: packages/simple_routes
        run: melos publish --no-dry-run --yes
